# Generated by Django 4.2.7 on 2024-05-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_listing_watchlist_remove_watchlist_listings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='listing',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='listing',
            field=models.ManyToManyField(null=True, related_name='listing_to_watch', to='auctions.listing'),
        ),
    ]
