# Generated by Django 4.2.7 on 2024-05-26 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_watchlist_listing_watchlist_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='listing',
            new_name='listings',
        ),
    ]
