# Generated by Django 4.2.7 on 2024-05-26 22:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_rename_user_listing_auction_lister_listing_watchlist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='watchlist',
        ),
        migrations.AddField(
            model_name='listing',
            name='watchlist',
            field=models.ManyToManyField(null=True, related_name='users_watching', to=settings.AUTH_USER_MODEL),
        ),
    ]
